### ISSUE TITLE
The code breaks when running in node

### ISSUE THREAD

**Issue by talbenbasat** [otalk/RTCPeerConnection#53]
I'm trying to use the package with node.js unsuccessfully. 
The code fails in traceablepeerconnection package (version 1.1.5 - latest)

after running these lines:
```
var PeerConnection = require('rtcpeerconnection');
var pc = new PeerConnection();
```

you receive this exception
```
../node_modules/rtcpeerconnection/node_modules/traceablepeerconnection/index.js:35
    this.peerconnection = new window.RTCPeerConnection(config, constraints);
                              ^

ReferenceError: window is not defined
    at new TraceablePeerConnection (.../node_modules/rtcpeerconnection/node_modules/traceablepeerconnection/index.js:35:31)
    at new PeerConnection (.../node_modules/rtcpeerconnection/rtcpeerconnection.js:115:15)
    at Object.<anonymous> (.../server.js:148:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
29 Oct 20:56:12 - [nodemon] app crashed - waiting for file changes before starting..
```

**Comment by fippo** [comment]
this module does not support nodejs. You might be interested in https://www.npmjs.com/package/wrtc
